const bussinessesList = [
  {
    id: '06a9a80c-c68d-407e-b434-cc23290b0665',
    name: 'đoàn ánh',
    address: 'đường lê văn hiến,Quận Ngũ Hành Sơn,Đà Nẵng',
    city: 'Việt Nam',
    postalCode: null,
    phoneContact: '0128 947 2011',
    emailContact: 'doananh234@gmail.com',
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: {
      friday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      monday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      sunday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      tuesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      saturday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      thursday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      wednesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
    },
    slug: 'doan-anh',
    isActive: true,
    country: null,
    coworkspace_url: null,
    main_image: null,
    main_img: null,
    min_price: null,
    currency: null,
    d_price: null,
    dm_price: null,
    is_featured: null,
    o_rate: null,
    total: null,
    xlat: null,
    xlng: null,
    isEnouvo: null,
    m_price: null,
    work_space_id: null,
    x_plan: null,
  },
  {
    id: 'fab0c2b4-d857-48e4-b50d-4110e2256302',
    name: 'Enouvo space',
    address: '15 Ta My Duat',
    city: 'Da Nang',
    postalCode: null,
    phoneContact: null,
    emailContact: 'enouvospace@gmail.com',
    website: 'https://enouvospace.com',
    shortIntroduction: null,
    aboutUs: null,
    workingTime: {
      friday: {
        isOpen: true,
        openTime: 25200,
        closeTime: 68400,
      },
      monday: {
        isOpen: true,
        openTime: 25200,
        closeTime: 68400,
      },
      sunday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      tuesday: {
        isOpen: true,
        openTime: 25200,
        closeTime: 68400,
      },
      saturday: {
        isOpen: true,
        openTime: 25200,
        closeTime: 68400,
      },
      thursday: {
        isOpen: true,
        openTime: 25200,
        closeTime: 68400,
      },
      wednesday: {
        isOpen: true,
        openTime: 25200,
        closeTime: 68400,
      },
    },
    slug: 'enouvo-space',
    isActive: true,
    country: null,
    coworkspace_url: null,
    main_image: null,
    main_img: null,
    min_price: null,
    currency: null,
    d_price: null,
    dm_price: null,
    is_featured: null,
    o_rate: null,
    total: null,
    xlat: null,
    xlng: null,
    isEnouvo: null,
    m_price: null,
    work_space_id: null,
    x_plan: null,
  },
  {
    id: '113b886b-b7f7-4e75-8347-3f23c6d85c0c',
    name: 'đoàn ánh',
    address: 'đường lê văn hiến,Quận Ngũ Hành Sơn,Đà Nẵng',
    city: 'Việt Nam',
    postalCode: null,
    phoneContact: '0128 947 2011',
    emailContact: 'doananh234@gmail.com',
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: {
      friday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      monday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      sunday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      tuesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      saturday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      thursday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      wednesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
    },
    slug: 'doan-anh',
    isActive: true,
    country: null,
    coworkspace_url: null,
    main_image: null,
    main_img: null,
    min_price: null,
    currency: null,
    d_price: null,
    dm_price: null,
    is_featured: null,
    o_rate: null,
    total: null,
    xlat: null,
    xlng: null,
    isEnouvo: null,
    m_price: null,
    work_space_id: null,
    x_plan: null,
  },
  {
    id: '343045bc-524e-4230-93e8-a6f184847bb7',
    name: 'đoàn ánh',
    address: 'đường lê văn hiến,Quận Ngũ Hành Sơn,Đà Nẵng',
    city: 'Việt Nam',
    postalCode: null,
    phoneContact: '0128 947 2011',
    emailContact: 'doananh234@gmail.com',
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: {
      friday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      monday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      sunday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      tuesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      saturday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      thursday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      wednesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
    },
    slug: 'doan-anh',
    isActive: true,
    country: null,
    coworkspace_url: null,
    main_image: null,
    main_img: null,
    min_price: null,
    currency: null,
    d_price: null,
    dm_price: null,
    is_featured: null,
    o_rate: null,
    total: null,
    xlat: null,
    xlng: null,
    isEnouvo: null,
    m_price: null,
    work_space_id: null,
    x_plan: null,
  },
  {
    id: '33b8bca7-26ef-49b4-bad8-d0530c87a7c7',
    name: 'Anh Doan',
    address: 'đường lê văn hiến,Quận Ngũ Hành Sơn,Đà Nẵng',
    city: 'Việt Nam',
    postalCode: null,
    phoneContact: '1289472011',
    emailContact: 'doananh234@gmail.com',
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: {
      friday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      monday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      sunday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      tuesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      saturday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      thursday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      wednesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
    },
    slug: 'anh-doan',
    isActive: true,
    country: null,
    coworkspace_url: null,
    main_image: null,
    main_img: null,
    min_price: null,
    currency: null,
    d_price: null,
    dm_price: null,
    is_featured: null,
    o_rate: null,
    total: null,
    xlat: null,
    xlng: null,
    isEnouvo: null,
    m_price: null,
    work_space_id: null,
    x_plan: null,
  },
  {
    id: '0ecb8147-3aab-4651-9ac0-0049465d9ce6',
    name: 'Anh Doan',
    address: 'đường lê văn hiến,Quận Ngũ Hành Sơn,Đà Nẵng',
    city: 'Việt Nam',
    postalCode: null,
    phoneContact: '1289472011',
    emailContact: 'doananh234@gmail.com',
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: {
      friday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      monday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      sunday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      tuesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      saturday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      thursday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      wednesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
    },
    slug: 'anh-doan',
    isActive: true,
    country: null,
    coworkspace_url: null,
    main_image: null,
    main_img: null,
    min_price: null,
    currency: null,
    d_price: null,
    dm_price: null,
    is_featured: null,
    o_rate: null,
    total: null,
    xlat: null,
    xlng: null,
    isEnouvo: null,
    m_price: null,
    work_space_id: null,
    x_plan: null,
  },
  {
    id: 'd12a4bc9-8620-4a1a-8893-1caa267b7752',
    name: 'đoàn ánh',
    address: 'đường lê văn hiến,Quận Ngũ Hành Sơn,Đà Nẵng',
    city: 'Việt Nam',
    postalCode: null,
    phoneContact: '0128 947 2011',
    emailContact: 'doananh234@gmail.com',
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: {
      friday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      monday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      sunday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      tuesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      saturday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      thursday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      wednesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
    },
    slug: 'doan-anh',
    isActive: true,
    country: null,
    coworkspace_url: null,
    main_image: null,
    main_img: null,
    min_price: null,
    currency: null,
    d_price: null,
    dm_price: null,
    is_featured: null,
    o_rate: null,
    total: null,
    xlat: null,
    xlng: null,
    isEnouvo: null,
    m_price: null,
    work_space_id: null,
    x_plan: null,
  },
  {
    id: '5bae2801-0f56-41f8-9e55-159778e5a04f',
    name: 'đoàn ánh',
    address: 'đường lê văn hiến,Quận Ngũ Hành Sơn,Đà Nẵng',
    city: 'Việt Nam',
    postalCode: null,
    phoneContact: '0128 947 2011',
    emailContact: 'doananh234@gmail.com',
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: {
      friday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      monday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      sunday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      tuesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      saturday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      thursday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      wednesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
    },
    slug: 'doan-anh',
    isActive: true,
    country: null,
    coworkspace_url: null,
    main_image: null,
    main_img: null,
    min_price: null,
    currency: null,
    d_price: null,
    dm_price: null,
    is_featured: null,
    o_rate: null,
    total: null,
    xlat: null,
    xlng: null,
    isEnouvo: null,
    m_price: null,
    work_space_id: null,
    x_plan: null,
  },
  {
    id: '53825638-dd05-4007-98cb-2bdf2b6badba',
    name: 'Ka Koncept',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'ka-koncept',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/ka-koncept',
    main_image: '/main-1498001043.JPG',
    main_img: 'JPG',
    min_price: '0.00',
    currency: 'VND',
    d_price: '180000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '4.9375',
    total: '16',
    xlat: '10.7710558',
    xlng: '106.6929764',
    isEnouvo: false,
    m_price: null,
    work_space_id: '2515',
    x_plan: 'FREE',
  },
  {
    id: '5125043e-6485-42dc-bcdc-3157e89d9347',
    name: 'Artfolio - Coworking Cafe',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'artfolio-coworking-cafe',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/artfolio-coworking-cafe',
    main_image: '/main-1500462392.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: null,
    dm_price: '2000000.00',
    is_featured: '0',
    o_rate: '4.3333',
    total: '3',
    xlat: '10.764353',
    xlng: '106.6813217',
    isEnouvo: false,
    m_price: null,
    work_space_id: '2970',
    x_plan: 'FREE',
  },
  {
    id: '137cc069-3b2a-4c26-ac68-10f6f736e2e5',
    name: 'Innovation Hub Business Incubator',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'innovation-hub-business-incubator',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/innovation-hub-business-incubator',
    main_image: '/main-1486005522.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'USD',
    d_price: '10.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '5.0000',
    total: '8',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '90.00',
    work_space_id: '3255',
    x_plan: 'FREE',
  },
  {
    id: '92edab3a-93dc-4216-9186-3396c9342880',
    name: 'Regus Indochina Riverside Office Tower',
    address: null,
    city: 'Da Nang',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'regus-indochina-riverside-office-tower',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/da-nang/regus-indochina-riverside-office-tower',
    main_image: '/main-1485163561.png',
    main_img: 'png',
    min_price: '0.00',
    currency: 'VND',
    d_price: '158000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '16.0699433',
    xlng: '108.2248062',
    isEnouvo: false,
    m_price: '0.00',
    work_space_id: '3278',
    x_plan: 'FREE',
  },
  {
    id: '76755ac9-c305-4c4d-85d4-8620b2eb27d2',
    name: 'Regus Saigon Tower',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'regus-saigon-tower',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/regus-saigon-tower',
    main_image: '/main-1485162620.png',
    main_img: 'png',
    min_price: '0.00',
    currency: 'VND',
    d_price: '208000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '10.7826872',
    xlng: '106.7011895',
    isEnouvo: false,
    m_price: '0.00',
    work_space_id: '3279',
    x_plan: 'FREE',
  },
  {
    id: 'f9dd647e-ed64-4408-b5c7-4efdf0de3bc7',
    name: 'Lucy Test',
    address: '195 Abc Street',
    city: null,
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: {
      friday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      monday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      sunday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      tuesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      saturday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      thursday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      wednesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
    },
    slug: 'lucy-test',
    isActive: true,
    country: null,
    coworkspace_url: null,
    main_image: null,
    main_img: null,
    min_price: null,
    currency: null,
    d_price: null,
    dm_price: null,
    is_featured: null,
    o_rate: null,
    total: null,
    xlat: null,
    xlng: null,
    isEnouvo: null,
    m_price: null,
    work_space_id: null,
    x_plan: null,
  },
  {
    id: 'de54939e-50da-42fd-9897-8cdd744b156c',
    name: 'Lucy Test',
    address: '195 Abc Street',
    city: null,
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: {
      friday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      monday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      sunday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      tuesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      saturday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      thursday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      wednesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
    },
    slug: 'lucy-test',
    isActive: true,
    country: null,
    coworkspace_url: null,
    main_image: null,
    main_img: null,
    min_price: null,
    currency: null,
    d_price: null,
    dm_price: null,
    is_featured: null,
    o_rate: null,
    total: null,
    xlat: null,
    xlng: null,
    isEnouvo: null,
    m_price: null,
    work_space_id: null,
    x_plan: null,
  },
  {
    id: '323efc46-1cbb-4cd9-98eb-fb8ecaa7fc29',
    name: 'Lucy Test',
    address: '195 Abc Street',
    city: null,
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: {
      friday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      monday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      sunday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      tuesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      saturday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      thursday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      wednesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
    },
    slug: 'lucy-test',
    isActive: true,
    country: null,
    coworkspace_url: null,
    main_image: null,
    main_img: null,
    min_price: null,
    currency: null,
    d_price: null,
    dm_price: null,
    is_featured: null,
    o_rate: null,
    total: null,
    xlat: null,
    xlng: null,
    isEnouvo: null,
    m_price: null,
    work_space_id: null,
    x_plan: null,
  },
  {
    id: '7e067f02-2533-4a0c-a481-7f30853609d2',
    name: 'đoàn ánh',
    address: 'đường lê văn hiến,Quận Ngũ Hành Sơn,Đà Nẵng',
    city: 'Việt Nam',
    postalCode: null,
    phoneContact: '0128 947 2011',
    emailContact: 'doananh234@gmail.com',
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: {
      friday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      monday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      sunday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      tuesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      saturday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      thursday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
      wednesday: {
        isOpen: false,
        openTime: 25200,
        closeTime: 68400,
      },
    },
    slug: 'doan-anh',
    isActive: true,
    country: null,
    coworkspace_url: null,
    main_image: null,
    main_img: null,
    min_price: null,
    currency: null,
    d_price: null,
    dm_price: null,
    is_featured: null,
    o_rate: null,
    total: null,
    xlat: null,
    xlng: null,
    isEnouvo: null,
    m_price: null,
    work_space_id: null,
    x_plan: null,
  },
  {
    id: '69e1f1eb-61ec-4cf6-9fa0-64b4ac48d866',
    name: 'Funwork',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'funwork',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/funwork',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '120000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '3.0000',
    total: '1',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '2500000.00',
    work_space_id: '21',
    x_plan: 'FREE',
  },
  {
    id: '679f562f-80d8-4c6e-a784-fee3c6dc45b9',
    name: 'Start Coworking Campus & Community',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'start-coworking-campus-and-community',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url:
      'vietnam/ho-chi-minh-city/start-coworking-campus-community',
    main_image: '/main-1524215451.jpg',
    main_img: 'jpg',
    min_price: '120000.00',
    currency: 'VND',
    d_price: '150000.00',
    dm_price: '3200000.00',
    is_featured: '2',
    o_rate: '5.0000',
    total: '24',
    xlat: '10.7952857',
    xlng: '106.7327199',
    isEnouvo: false,
    m_price: '1900000.00',
    work_space_id: '29',
    x_plan: 'FEATURED',
  },
  {
    id: '8533b470-bab4-44b7-b3a8-77ed94aa3832',
    name: 'Saigon Coworking',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'saigon-coworking',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/saigon-coworking',
    main_image: '/main.jpeg',
    main_img: 'jpeg',
    min_price: '0.00',
    currency: 'USD',
    d_price: '0.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '4.0000',
    total: '1',
    xlat: '10.797684',
    xlng: '106.6860679',
    isEnouvo: false,
    m_price: '95.00',
    work_space_id: '50',
    x_plan: 'FREE',
  },
  {
    id: 'e68be94d-b2fb-464d-bef9-bb8b80d79d2e',
    name: 'Work Saigon',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'work-saigon',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/work-saigon',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '0.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '4.3333',
    total: '3',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '2000000.00',
    work_space_id: '51',
    x_plan: 'FREE',
  },
  {
    id: 'd94592dd-3c95-4e23-a5dc-6c3c666916ca',
    name: 'iHouse',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'ihouse',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/ihouse',
    main_image: 'vietnam/hanoi/ihouse/main-1510390938.jpg',
    main_img: 'jpg',
    min_price: '150.00',
    currency: 'VND',
    d_price: '120000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '21.0320346',
    xlng: '105.8047666',
    isEnouvo: false,
    m_price: '1400000.00',
    work_space_id: '71',
    x_plan: 'FREE',
  },
  {
    id: 'a575b21e-1c00-4637-984b-9b5da4b89456',
    name: 'Click Space',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'click-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/click-space',
    main_image: '/main.jpeg',
    main_img: 'jpeg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '0.00',
    dm_price: '0.00',
    is_featured: '0',
    o_rate: '5.0000',
    total: '1',
    xlat: '21.069022',
    xlng: '105.822739',
    isEnouvo: false,
    m_price: '1200000.00',
    work_space_id: '72',
    x_plan: 'FREE',
  },
  {
    id: '0132a3a3-9eb1-425c-8a1f-7f1b095746e5',
    name: 'HUB IT',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'hub-it',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/hub-it',
    main_image: '/main.png',
    main_img: 'png',
    min_price: '20.00',
    currency: 'VND',
    d_price: '20.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '150.00',
    work_space_id: '73',
    x_plan: 'FREE',
  },
  {
    id: 'dfc0ea1a-9ed8-4f45-ac5e-71e821a38667',
    name: 'HATCH! NEST Coworking Space',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'hatch-nest-coworking-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/hatch-nest-coworking-space',
    main_image: '/main-1510052494.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '150000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '4.6667',
    total: '3',
    xlat: '21.035078',
    xlng: '105.82372',
    isEnouvo: false,
    m_price: '15000000.00',
    work_space_id: '74',
    x_plan: 'FREE',
  },
  {
    id: '821ba551-291c-41ba-bc4a-1c3905590c5c',
    name: 'Hatch Nest - 7',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'hatch-nest-7',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/hatch-nest-7',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '7.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '75.00',
    work_space_id: '75',
    x_plan: 'FREE',
  },
  {
    id: 'eb55a891-63bb-48ec-a36f-16f852015f77',
    name: 'DreamPlex',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'dreamplex',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/dreamplex',
    main_image: '/main-1490333600.jpeg',
    main_img: 'jpeg',
    min_price: '150000.00',
    currency: 'VND',
    d_price: '150000.00',
    dm_price: '0.00',
    is_featured: '0',
    o_rate: '5.0000',
    total: '8',
    xlat: '10.7830976',
    xlng: '106.7049231',
    isEnouvo: false,
    m_price: '2000000.00',
    work_space_id: '471',
    x_plan: 'FREE',
  },
  {
    id: 'caa2814a-7b67-49fa-88f8-c9f28ed2e734',
    name: 'Citihub Co-working Space & Coffee',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'citihub-co-working-space-and-coffee',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/citihub-co-working-space-coffee',
    main_image: '/main-1501565320.jpg',
    main_img: 'jpg',
    min_price: '100000.00',
    currency: 'VND',
    d_price: '100000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '10.7902054',
    xlng: '106.69931180000003',
    isEnouvo: false,
    m_price: '2000000.00',
    work_space_id: '800',
    x_plan: 'FREE',
  },
  {
    id: '62192e74-7e2a-4c05-9a6a-97980a266278',
    name: 'HanoiHub Coworking Space 1',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'hanoihub-coworking-space-1',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/hanoihub-coworking-space-1',
    main_image: '/main-1500636802.jpg',
    main_img: 'jpg',
    min_price: '150000.00',
    currency: 'VND',
    d_price: '150000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '4.8333',
    total: '6',
    xlat: '21.0186699',
    xlng: '105.81679610000003',
    isEnouvo: false,
    m_price: '1800000.00',
    work_space_id: '1654',
    x_plan: 'FREE',
  },
  {
    id: '7c6cecdc-538d-49b5-ac71-9650fe717551',
    name: 'Coworking Space by TheVentures',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'coworking-space-by-theventures',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/coworking-space-by-theventures',
    main_image: '/main.jpeg',
    main_img: 'jpeg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '100000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '10.823099',
    xlng: '106.629664',
    isEnouvo: false,
    m_price: '0.00',
    work_space_id: '1807',
    x_plan: 'FREE',
  },
  {
    id: '892d81d2-a5e2-4113-b69d-069f74bb8510',
    name: 'BIGWork',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'bigwork',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/bigwork',
    main_image: '/main-1484885088.JPG',
    main_img: 'JPG',
    min_price: '140000.00',
    currency: 'VND',
    d_price: '140000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '4.0000',
    total: '1',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '2000000.00',
    work_space_id: '1837',
    x_plan: 'FREE',
  },
  {
    id: 'b0ee25fa-35bc-4176-ab3f-40162f20a819',
    name: 'Deska',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'deska',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/deska',
    main_image: '/main.png',
    main_img: 'png',
    min_price: '130000.00',
    currency: 'VND',
    d_price: '130000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '1800000.00',
    work_space_id: '2186',
    x_plan: 'FREE',
  },
  {
    id: '239df5bd-ffc1-4bfe-9168-0dcf52719678',
    name: 'CirCO Coworking Space',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'circo-coworking-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/circo-coworking-space',
    main_image: '/main-1488017339.jpg',
    main_img: 'jpg',
    min_price: '150000.00',
    currency: 'VND',
    d_price: '150000.00',
    dm_price: '0.00',
    is_featured: '0',
    o_rate: '4.9167',
    total: '12',
    xlat: '10.7597564',
    xlng: '106.69861360000004',
    isEnouvo: false,
    m_price: '1800000.00',
    work_space_id: '2219',
    x_plan: 'FREE',
  },
  {
    id: '8cc083bd-f1e4-4216-b357-2a90284c3caf',
    name: 'Go WORK',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'go-work',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/go-work',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '100000.00',
    currency: 'VND',
    d_price: '100000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '5.0000',
    total: '1',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '1900000.00',
    work_space_id: '2274',
    x_plan: 'FREE',
  },
  {
    id: '927fbe1a-05a9-4b7c-a3df-d87ad88f52d3',
    name: 'Regus Me Linh Point Tower',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'regus-me-linh-point-tower',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/regus-me-linh-point-tower',
    main_image: '/main-1485161626.png',
    main_img: 'png',
    min_price: '0.00',
    currency: 'VND',
    d_price: '202000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '10.7746075',
    xlng: '106.7060445',
    isEnouvo: false,
    m_price: '0.00',
    work_space_id: '3280',
    x_plan: 'FREE',
  },
  {
    id: 'c0e753ee-1050-4ea8-9355-c8a6bc15814a',
    name: 'Regus Daeha Business Centre',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'regus-daeha-business-centre',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/regus-daeha-business-centre',
    main_image: '/main-1485160539.jpeg',
    main_img: 'jpeg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '110000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '21.0311138',
    xlng: '105.8125641',
    isEnouvo: false,
    m_price: '0.00',
    work_space_id: '3282',
    x_plan: 'FREE',
  },
  {
    id: '043026a8-baf2-4d25-b2ef-d30b2b501a21',
    name: 'Regus Press Club',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'regus-press-club',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/regus-press-club',
    main_image: '/main-1485157966.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '186000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '21.025253',
    xlng: '105.856741',
    isEnouvo: false,
    m_price: '0.00',
    work_space_id: '3284',
    x_plan: 'FREE',
  },
  {
    id: '4919fe3d-c5ad-48e8-a07c-9b04e14947aa',
    name: 'Enouvo Space',
    address: null,
    city: 'Da Nang',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'enouvo-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/da-nang/enouvo-space',
    main_image: '/main-1517394441.jpg',
    main_img: 'jpg',
    min_price: '90000.00',
    currency: 'VND',
    d_price: '90000.00',
    dm_price: '20000000.00',
    is_featured: '2',
    o_rate: '4.9412',
    total: '17',
    xlat: '16.069868',
    xlng: '108.23430099999996',
    isEnouvo: true,
    m_price: '1800000.00',
    work_space_id: '3310',
    x_plan: 'FEATURED',
  },
  {
    id: '12acb90c-1da9-49ae-b880-d6c7f2f6e8ec',
    name: 'SmartDev Coworking Space',
    address: null,
    city: 'Da Nang',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'smartdev-coworking-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/da-nang/smartdev-coworking-space',
    main_image: '/main-1486525879.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'USD',
    d_price: '0.00',
    dm_price: '0.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '200.00',
    work_space_id: '3459',
    x_plan: 'FREE',
  },
  {
    id: 'eec8f8fc-29a7-42d1-ba57-dd0d669253e1',
    name: 'the HUB',
    address: null,
    city: 'Da Nang',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'the-hub',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/da-nang/the-hub',
    main_image: '/main-1487734137.jpg',
    main_img: 'jpg',
    min_price: '120000.00',
    currency: 'VND',
    d_price: '120000.00',
    dm_price: '3700000.00',
    is_featured: '0',
    o_rate: '5.0000',
    total: '5',
    xlat: '16.0660007',
    xlng: '108.2234651',
    isEnouvo: false,
    m_price: '2300000.00',
    work_space_id: '3603',
    x_plan: 'FREE',
  },
  {
    id: '77b5be85-fe38-4aca-b8a2-3a4531017782',
    name: 'HEXAGON - Danang Startup Center',
    address: null,
    city: 'Da Nang',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'hexagon-danang-startup-center',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/da-nang/hexagon-danang-startup-center',
    main_image: '/main-1490323368.jpg',
    main_img: 'jpg',
    min_price: '120000.00',
    currency: 'VND',
    d_price: '120000.00',
    dm_price: '2000000.00',
    is_featured: '0',
    o_rate: '4.7500',
    total: '8',
    xlat: '16.067019',
    xlng: '108.213397',
    isEnouvo: false,
    m_price: '1500000.00',
    work_space_id: '3609',
    x_plan: 'FREE',
  },
  {
    id: 'd511ec2d-7e9d-4b2a-985c-36beec85307c',
    name: 'Dreamplex2',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'dreamplex2',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/dreamplex2',
    main_image: '/main-1496200880.jpeg',
    main_img: 'jpeg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '150000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '10.801288',
    xlng: '106.7086204',
    isEnouvo: false,
    m_price: '1800000.00',
    work_space_id: '3619',
    x_plan: 'FREE',
  },
  {
    id: '6d04a96b-9072-43b3-9d3b-2da8d776ab0d',
    name: 'Bizcovery Coworking',
    address: null,
    city: 'Da Nang',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'bizcovery-coworking',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/da-nang/bizcovery-coworking',
    main_image: '/main-1496219408.jpeg',
    main_img: 'jpeg',
    min_price: '0.00',
    currency: 'VND',
    d_price: null,
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '2000000.00',
    work_space_id: '3620',
    x_plan: 'FREE',
  },
  {
    id: 'c3d1927e-f865-48ca-8012-baa61d3579eb',
    name: 'Moonwork Coworking Space',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'moonwork-coworking-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/moonwork-coworking-space',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: null,
    dm_price: null,
    is_featured: '2',
    o_rate: '4.8571',
    total: '7',
    xlat: '21.0319298',
    xlng: '105.8414346',
    isEnouvo: false,
    m_price: null,
    work_space_id: '3659',
    x_plan: 'FEATURED',
  },
  {
    id: '60e9a4df-534b-41c6-a198-8a6350f9252b',
    name: 'Hub Hoi An',
    address: null,
    city: 'Hoi An',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'hub-hoi-an',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hoi-an/hub-hoi-an',
    main_image: '/main-1517035628.jpg',
    main_img: 'jpg',
    min_price: '140000.00',
    currency: 'VND',
    d_price: '210000.00',
    dm_price: null,
    is_featured: '2',
    o_rate: '4.9394',
    total: '33',
    xlat: '15.8910899',
    xlng: '108.344189',
    isEnouvo: false,
    m_price: '4000000.00',
    work_space_id: '4026',
    x_plan: 'FEATURED',
  },
  {
    id: '066a4861-97a1-4175-ba7d-3e3ce9d2cb1d',
    name: 'CEO SUITE - Hanoi Lotte Center',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'ceo-suite-hanoi-lotte-center',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/ceo-suite-hanoi-lotte-center',
    main_image: '/main-1520324389.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '0.00',
    dm_price: '0.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '21.032323',
    xlng: '105.812769',
    isEnouvo: false,
    m_price: '0.00',
    work_space_id: '4350',
    x_plan: 'FREE',
  },
  {
    id: '94858998-ce84-4731-a61c-32fbfea3e0ea',
    name: 'DNC - Danang Coworking Space',
    address: null,
    city: 'Da Nang',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'dnc-danang-coworking-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/da-nang/dnc-danang-coworking-space',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '66000.00',
    dm_price: '1320000.00',
    is_featured: '0',
    o_rate: '5.0000',
    total: '2',
    xlat: '16.074971',
    xlng: '108.223677',
    isEnouvo: false,
    m_price: '880000.00',
    work_space_id: '4363',
    x_plan: 'FREE',
  },
  {
    id: 'dfe319ef-9555-4877-b05c-4ebab05eb95b',
    name: 'the Hive Saigon',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'the-hive-saigon',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/the-hive-saigon',
    main_image: '/main-1516848760.jpg',
    main_img: 'jpg',
    min_price: '150000.00',
    currency: 'VND',
    d_price: '150000.00',
    dm_price: '3500000.00',
    is_featured: '0',
    o_rate: '5.0000',
    total: '4',
    xlat: '10.8036296',
    xlng: '106.735047',
    isEnouvo: false,
    m_price: '2000000.00',
    work_space_id: '4884',
    x_plan: 'DIRECT',
  },
  {
    id: '735725c5-a213-460c-90cc-a637188003ed',
    name: 'The Rooftop Garden Co-working',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'the-rooftop-garden-co-working',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/the-rooftop-garden-co-working',
    main_image: '/main.JPG',
    main_img: 'JPG',
    min_price: '0.00',
    currency: 'VND',
    d_price: null,
    dm_price: null,
    is_featured: '0',
    o_rate: '4.4000',
    total: '5',
    xlat: '10.7880388',
    xlng: '106.6962628',
    isEnouvo: false,
    m_price: '800000.00',
    work_space_id: '4973',
    x_plan: 'FREE',
  },
  {
    id: '85e52e60-5ea2-4cb0-aa8a-8f05c8023b11',
    name: 'CoPLUS working space and incubation',
    address: null,
    city: 'Hue',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'coplus-working-space-and-incubation',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hue/coplus-working-space-and-incubation',
    main_image: '/main.JPG',
    main_img: 'JPG',
    min_price: '0.00',
    currency: 'VND',
    d_price: '66000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '4.0000',
    total: '1',
    xlat: '16.4649217',
    xlng: '107.5948995',
    isEnouvo: false,
    m_price: null,
    work_space_id: '5023',
    x_plan: 'FREE',
  },
  {
    id: '1231a642-ae19-4570-9ef6-7682d1b128ba',
    name: 'Fablab Saigon',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'fablab-saigon',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/fablab-saigon',
    main_image: '/main-1503561979.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: null,
    dm_price: '1300000.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '600000.00',
    work_space_id: '5083',
    x_plan: 'FREE',
  },
  {
    id: 'c68f54a7-2cc2-44ab-99a7-f7119fc339c5',
    name: 'Pepper House Asia',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'pepper-house-asia',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/pepper-house-asia',
    main_image: '/main.jpeg',
    main_img: 'jpeg',
    min_price: '0.00',
    currency: 'USD',
    d_price: '10.00',
    dm_price: '0.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '10.791929',
    xlng: '106.704744',
    isEnouvo: false,
    m_price: '150.00',
    work_space_id: '5086',
    x_plan: 'FREE',
  },
  {
    id: 'bb53f7d9-ed48-49c4-970c-7208c1e0dea4',
    name: 'OfficeHub',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'officehub',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/officehub',
    main_image: '/main.jpeg',
    main_img: 'jpeg',
    min_price: '0.00',
    currency: 'USD',
    d_price: '0.00',
    dm_price: '0.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '10.7738465',
    xlng: '106.7054735',
    isEnouvo: false,
    m_price: '0.00',
    work_space_id: '5092',
    x_plan: 'FREE',
  },
  {
    id: 'f86df937-17b7-4b89-a3c7-e693cf36f800',
    name: 'Texo Spatium',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'texo-spatium',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/texo-spatium',
    main_image: '/main.jpeg',
    main_img: 'jpeg',
    min_price: '0.00',
    currency: 'USD',
    d_price: '8.00',
    dm_price: '110.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '0.00',
    work_space_id: '5094',
    x_plan: 'FREE',
  },
  {
    id: 'f7ba07b8-4a53-4aac-aa5b-f95f4b2981f9',
    name: 'Think in a Box',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'think-in-a-box',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/think-in-a-box',
    main_image: '/main-1512031253.png',
    main_img: 'png',
    min_price: '0.00',
    currency: 'VND',
    d_price: '99000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '10.762718',
    xlng: '106.693521',
    isEnouvo: false,
    m_price: '1400000.00',
    work_space_id: '5095',
    x_plan: 'FREE',
  },
  {
    id: 'caff2710-e1f3-42be-981c-87360df139dd',
    name: 'ITP OFFICE',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'itp-office',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/itp-office',
    main_image: '/main.jpeg',
    main_img: 'jpeg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '0.00',
    dm_price: '0.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '900000.00',
    work_space_id: '5096',
    x_plan: 'FREE',
  },
  {
    id: 'aa18e641-9a00-4fd3-ac0d-b94972523a79',
    name: 'Toong - The Oxygen',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'toong-the-oxygen',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/toong-the-oxygen',
    main_image: '/main-1507257424.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '120000.00',
    dm_price: '3999000.00',
    is_featured: '0',
    o_rate: '5.0000',
    total: '1',
    xlat: '10.8049501',
    xlng: '106.7511487',
    isEnouvo: false,
    m_price: '1900000.00',
    work_space_id: '5097',
    x_plan: 'FREE',
  },
  {
    id: '2389c57c-df41-4759-bdff-81bd80c31f2c',
    name: 'Rom Casa Hotel Da Nang',
    address: null,
    city: 'Da Nang',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'rom-casa-hotel-da-nang',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/da-nang/rom-casa-hotel-da-nang',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '9.80',
    currency: 'USD',
    d_price: '9.80',
    dm_price: '210.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '16.0544068',
    xlng: '108.2021667',
    isEnouvo: false,
    m_price: '210.00',
    work_space_id: '5104',
    x_plan: 'FREE',
  },
  {
    id: '5ec85ad6-ed54-44c6-870f-5a01ce3791aa',
    name: 'Toong - DNC Coworking Space',
    address: null,
    city: 'Da Nang',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'toong-dnc-coworking-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/da-nang/toong-dnc-coworking-space',
    main_image: '/main.jpeg',
    main_img: 'jpeg',
    min_price: '0.00',
    currency: 'VND',
    d_price: null,
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '899000.00',
    work_space_id: '5105',
    x_plan: 'FREE',
  },
  {
    id: '225d008e-ecf5-430f-a23c-df52e2a55d8b',
    name: 'Toong - Hoang Dao Thuy',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'toong-hoang-dao-thuy',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/toong-hoang-dao-thuy',
    main_image: '/main-1505985870.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '120000.00',
    dm_price: '3999000.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '21.0073758',
    xlng: '105.8024514',
    isEnouvo: false,
    m_price: '1900000.00',
    work_space_id: '5106',
    x_plan: 'FREE',
  },
  {
    id: '4584579a-a7ee-4267-bc7b-07212963ed82',
    name: 'Toong - Trang Thi',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'toong-trang-thi',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/toong-trang-thi',
    main_image: '/main-1505987553.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '120000.00',
    dm_price: '3900000.00',
    is_featured: '0',
    o_rate: '4.0000',
    total: '4',
    xlat: '21.026752',
    xlng: '105.849193',
    isEnouvo: false,
    m_price: '1900000.00',
    work_space_id: '5107',
    x_plan: 'FREE',
  },
  {
    id: '122d843b-ae44-433c-96ae-f5c3136bc1e6',
    name: 'Toong - To Ngoc Van',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'toong-to-ngoc-van',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/toong-to-ngoc-van',
    main_image: '/main-1505988419.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '120000.00',
    dm_price: '3999000.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '1900000.00',
    work_space_id: '5108',
    x_plan: 'FREE',
  },
  {
    id: '085086eb-e899-42c2-9106-76bc75194e56',
    name: 'UP Coworking Space',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'up-coworking-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/up-coworking-space',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '0.00',
    dm_price: '3000000.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '21.012589',
    xlng: '105.863218',
    isEnouvo: false,
    m_price: '1500000.00',
    work_space_id: '5109',
    x_plan: 'FREE',
  },
  {
    id: 'fe242025-080d-4dd8-ae06-c1d4b833c2c8',
    name: 'VSV Corner',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'vsv-corner',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/vsv-corner',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '150000.00',
    dm_price: '3000000.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '21.022595',
    xlng: '105.8532199',
    isEnouvo: false,
    m_price: '0.00',
    work_space_id: '5110',
    x_plan: 'FREE',
  },
  {
    id: '4c2b7fa2-c751-40e7-8a52-0975c37f7aa0',
    name: 'Egg Accelerator Saigon',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'egg-accelerator-saigon',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/egg-accelerator-saigon',
    main_image: '/main.jpeg',
    main_img: 'jpeg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '0.00',
    dm_price: '0.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '10.7929955',
    xlng: '106.7179647',
    isEnouvo: false,
    m_price: '0.00',
    work_space_id: '5163',
    x_plan: 'FREE',
  },
  {
    id: 'e5b19020-eea3-4f1c-8619-8a543acd9ef5',
    name: 'The Mahogany',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'the-mahogany',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/the-mahogany',
    main_image: '/main-1502166560.JPG',
    main_img: 'JPG',
    min_price: '0.00',
    currency: 'VND',
    d_price: '120000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '5.0000',
    total: '2',
    xlat: '21.0177909',
    xlng: '105.8239967',
    isEnouvo: false,
    m_price: '2000000.00',
    work_space_id: '5244',
    x_plan: 'FREE',
  },
  {
    id: '072ec7e5-9f7d-4711-82fc-b48bf9935d93',
    name: 'Workyos',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'workyos',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/workyos',
    main_image: '/main-1522377528.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '150000.00',
    dm_price: '3500000.00',
    is_featured: '0',
    o_rate: '4.6667',
    total: '12',
    xlat: '10.7787131',
    xlng: '106.6796195',
    isEnouvo: false,
    m_price: '2500000.00',
    work_space_id: '5249',
    x_plan: 'FREE',
  },
  {
    id: 'fe3bf003-d419-4a37-b2bb-779eb8f8b62b',
    name: 'CirCO District 1 Coworking Space',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'circo-district-1-coworking-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url:
      'vietnam/ho-chi-minh-city/circo-district-1-coworking-space',
    main_image: '/main-1502442034.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '0.00',
    dm_price: '0.00',
    is_featured: '0',
    o_rate: '5.0000',
    total: '6',
    xlat: '10.7709374',
    xlng: '106.693057',
    isEnouvo: false,
    m_price: '0.00',
    work_space_id: '5272',
    x_plan: 'FREE',
  },
  {
    id: '562bcf37-b7b7-4060-9046-f6699804dc66',
    name: 'CO-SPACE',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'co-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/co-space',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '250.00',
    dm_price: '5800000.00',
    is_featured: '2',
    o_rate: '5.0000',
    total: '4',
    xlat: '10.8038828',
    xlng: '106.7354412',
    isEnouvo: false,
    m_price: '1800000.00',
    work_space_id: '5579',
    x_plan: 'FEATURED',
  },
  {
    id: '37f34781-695e-446b-b12e-b0939d2ff37a',
    name: 'UP Coworking Space',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'up-coworking-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/up-coworking-space',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '200000.00',
    dm_price: '2500000.00',
    is_featured: '0',
    o_rate: '5.0000',
    total: '1',
    xlat: '10.7734543',
    xlng: '106.6598146',
    isEnouvo: false,
    m_price: '1500000.00',
    work_space_id: '5694',
    x_plan: 'FREE',
  },
  {
    id: '4f96318f-2a12-4cfb-ba20-dc651725ea6f',
    name: 'Neighborhub Coworking Space',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'neighborhub-coworking-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/neighborhub-coworking-space',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '120000.00',
    dm_price: '0.00',
    is_featured: '0',
    o_rate: '4.7500',
    total: '4',
    xlat: '10.7832369',
    xlng: '106.6961918',
    isEnouvo: false,
    m_price: '1800000.00',
    work_space_id: '5695',
    x_plan: 'FREE',
  },
  {
    id: 'c5402334-bb72-4273-8253-63591f254ed7',
    name: 'CADO COWORKING SPACE',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'cado-coworking-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/cado-coworking-space',
    main_image: '/main-1509951840.jpg',
    main_img: 'jpg',
    min_price: '140000.00',
    currency: 'VND',
    d_price: '100000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '3.2500',
    total: '4',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '1600000.00',
    work_space_id: '5926',
    x_plan: 'FREE',
  },
  {
    id: '028ad128-bde8-4b3b-b990-a77e5f8ffdd1',
    name: 'Manna Co-working Space',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'manna-co-working-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/manna-co-working-space',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '80000.00',
    currency: 'VND',
    d_price: '80000.00',
    dm_price: '0.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '21.015756755136',
    xlng: '105.78200514656',
    isEnouvo: false,
    m_price: '1300000.00',
    work_space_id: '6412',
    x_plan: 'FREE',
  },
  {
    id: 'a4135d62-3ca8-4d35-a60e-7df7ce447a2b',
    name: 'G-Office - Hado Airport Branch',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'g-office-hado-airport-branch',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/g-office-hado-airport-branch',
    main_image: '/main.jpeg',
    main_img: 'jpeg',
    min_price: '0.00',
    currency: 'VND',
    d_price: null,
    dm_price: '0.00',
    is_featured: '0',
    o_rate: '5.0000',
    total: '1',
    xlat: '10.813247',
    xlng: '106.666182',
    isEnouvo: false,
    m_price: '0.00',
    work_space_id: '6455',
    x_plan: 'FREE',
  },
  {
    id: '48d58046-d4db-4814-b0b1-eaf8838f68b5',
    name: 'CEO SUITE - Vietcombank Tower',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'ceo-suite-vietcombank-tower',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/ceo-suite-vietcombank-tower',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '0.00',
    dm_price: '0.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '1',
    xlat: '10.7756261',
    xlng: '106.7059261',
    isEnouvo: false,
    m_price: '0.00',
    work_space_id: '6568',
    x_plan: 'FREE',
  },
  {
    id: 'df3178a0-4bdb-492e-9412-4aef094c0ad8',
    name: 'Belink Office',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'belink-office',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/belink-office',
    main_image: '/main.jpeg',
    main_img: 'jpeg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '250000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '4.6667',
    total: '3',
    xlat: '21.010752',
    xlng: '105.848959',
    isEnouvo: false,
    m_price: null,
    work_space_id: '6757',
    x_plan: 'FREE',
  },
  {
    id: '289e2c83-7a5a-4564-8527-8e23ce831d48',
    name: 'ViS Office Da Nang',
    address: null,
    city: 'Da Nang',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'vis-office-da-nang',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/da-nang/vis-office-da-nang',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '85000.00',
    dm_price: '1950000.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '16.0801559',
    xlng: '108.2199615',
    isEnouvo: false,
    m_price: '1500000.00',
    work_space_id: '6863',
    x_plan: 'FREE',
  },
  {
    id: 'cbb8b039-6092-4ef4-9de1-91787146c777',
    name: 'eSpace Coworking',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'espace-coworking',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/espace-coworking',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '150000.00',
    currency: 'VND',
    d_price: '150000.00',
    dm_price: '3900000.00',
    is_featured: '0',
    o_rate: '5.0000',
    total: '5',
    xlat: '21.025586088731',
    xlng: '105.85460965145',
    isEnouvo: false,
    m_price: '2900000.00',
    work_space_id: '6955',
    x_plan: 'FREE',
  },
  {
    id: '7eb7fc7c-ea17-48c0-b021-52e7a557ecff',
    name: 'Officespot Coworking',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'officespot-coworking',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/officespot-coworking',
    main_image: '/main-1516856636.jpeg',
    main_img: 'jpeg',
    min_price: '140000.00',
    currency: 'VND',
    d_price: '140000.00',
    dm_price: '3800000.00',
    is_featured: '0',
    o_rate: '5.0000',
    total: '4',
    xlat: '10.7533629',
    xlng: '106.7317735',
    isEnouvo: false,
    m_price: '1800000.00',
    work_space_id: '7002',
    x_plan: 'FREE',
  },
  {
    id: '3b189dda-1aa5-42a2-9c88-200fa4db85e3',
    name: 'COoffice.VN',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'coofficevn',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/coofficevn',
    main_image: '/main-1517969854.png',
    main_img: 'png',
    min_price: '250000.00',
    currency: 'VND',
    d_price: '250000.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '5000000.00',
    work_space_id: '7086',
    x_plan: 'FREE',
  },
  {
    id: 'be9163b8-b78e-44d7-8471-7d3e508e9a9e',
    name: 'HanoiHub Coworking Space 2',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'hanoihub-coworking-space-2',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/hanoihub-coworking-space-2',
    main_image: '/main.jpeg',
    main_img: 'jpeg',
    min_price: '120000.00',
    currency: 'VND',
    d_price: '120000.00',
    dm_price: '2500000.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '21.0162678',
    xlng: '105.8092129',
    isEnouvo: false,
    m_price: '1800000.00',
    work_space_id: '7105',
    x_plan: 'FREE',
  },
  {
    id: '85137088-b6ef-483c-9663-8f7df45066bc',
    name: 'Y-Nest Coworking Space',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'y-nest-coworking-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/y-nest-coworking-space',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '100000.00',
    currency: 'VND',
    d_price: '100000.00',
    dm_price: '2200000.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '20.9997366',
    xlng: '105.8698744',
    isEnouvo: false,
    m_price: '1600000.00',
    work_space_id: '7362',
    x_plan: 'FREE',
  },
  {
    id: 'cfff9dc0-c9e9-482f-944e-0e37701a48a4',
    name: 'Conroy Tower',
    address: null,
    city: 'Da Nang',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'conroy-tower',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/da-nang/conroy-tower',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '9.00',
    currency: 'USD',
    d_price: '9.00',
    dm_price: null,
    is_featured: '0',
    o_rate: '5.0000',
    total: '1',
    xlat: '16.0730046',
    xlng: '108.2006528',
    isEnouvo: false,
    m_price: '150.00',
    work_space_id: '7363',
    x_plan: 'FREE',
  },
  {
    id: '0f433881-fdbe-4bd3-be81-b34b83f66c35',
    name: 'QSpace',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'qspace',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/qspace',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: '150000.00',
    dm_price: '2600000.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '10.786188',
    xlng: '106.698401',
    isEnouvo: false,
    m_price: '2000000.00',
    work_space_id: '7633',
    x_plan: 'FREE',
  },
  {
    id: '5c00f118-76b7-47f3-9a17-92f9d098dc1d',
    name: 'Toong - Minh Khai, Ho Chi Minh City',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'toong-minh-khai-ho-chi-minh-city',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url:
      'vietnam/ho-chi-minh-city/toong-minh-khai-ho-chi-minh-city',
    main_image: '/main.JPG',
    main_img: 'JPG',
    min_price: '0.00',
    currency: 'VND',
    d_price: '120000.00',
    dm_price: '3900000.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '10.7779476',
    xlng: '106.6929065',
    isEnouvo: false,
    m_price: '1900000.00',
    work_space_id: '7670',
    x_plan: 'FREE',
  },
  {
    id: '1d3ce819-971f-40ba-a779-ff2f9d90f919',
    name: 'Vuong Tron Giac',
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'vuong-tron-giac',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/vuong-tron-giac',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '150000.00',
    currency: 'VND',
    d_price: '150000.00',
    dm_price: '2200000.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '1800000.00',
    work_space_id: '7757',
    x_plan: 'FREE',
  },
  {
    id: 'dea4f4de-0db0-4762-acd9-dc17a8415276',
    name: 'The Learning Hub',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'the-learning-hub',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/the-learning-hub',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '100000.00',
    currency: 'VND',
    d_price: '100000.00',
    dm_price: '0.00',
    is_featured: '0',
    o_rate: '5.0000',
    total: '11',
    xlat: '21.025257',
    xlng: '105.855192',
    isEnouvo: false,
    m_price: '750000.00',
    work_space_id: '7950',
    x_plan: 'FREE',
  },
  {
    id: 'fbea6349-7bca-413f-8642-b94df5124d4e',
    name: 'KiCoworking Space',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'kicoworking-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/kicoworking-space',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '120000.00',
    currency: 'VND',
    d_price: '120000.00',
    dm_price: '250000.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '21.0025828',
    xlng: '105.8011894',
    isEnouvo: false,
    m_price: '1500000.00',
    work_space_id: '7971',
    x_plan: 'FREE',
  },
  {
    id: '31ac0d50-aa33-4a86-865a-bec9412678ec',
    name: 'naked Hub Indochina Plaza Hanoi',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'naked-hub-indochina-plaza-hanoi',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/naked-hub-indochina-plaza-hanoi',
    main_image: '/main-1524824049.jpg',
    main_img: 'jpg',
    min_price: '0.00',
    currency: 'VND',
    d_price: null,
    dm_price: '4000000.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: null,
    xlng: null,
    isEnouvo: false,
    m_price: '2300000.00',
    work_space_id: '8027',
    x_plan: 'FREE',
  },
  {
    id: '33ab7830-bfbb-4f45-8b96-d564e991a736',
    name: 'UP Co-woking Space',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'up-co-woking-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/up-co-woking-space',
    main_image: '/main.png',
    main_img: 'png',
    min_price: '300000.00',
    currency: 'VND',
    d_price: '300000.00',
    dm_price: '3000000.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '21.016341',
    xlng: '105.814904',
    isEnouvo: false,
    m_price: '4000000.00',
    work_space_id: '8032',
    x_plan: 'FREE',
  },
  {
    id: 'df0c2622-9636-45fc-b11d-c06f672ec5ce',
    name: "F'enhance Workspace",
    address: null,
    city: 'Ho Chi Minh City',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'fenhance-workspace',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/ho-chi-minh-city/fenhance-workspace',
    main_image: '/main.png',
    main_img: 'png',
    min_price: '0.00',
    currency: 'VND',
    d_price: null,
    dm_price: null,
    is_featured: '0',
    o_rate: '5.0000',
    total: '1',
    xlat: '10.7858713',
    xlng: '106.6851001',
    isEnouvo: false,
    m_price: null,
    work_space_id: '8072',
    x_plan: 'FREE',
  },
  {
    id: '43b82676-1f9b-48f2-9184-3a4bde79f18b',
    name: 'MegaShare Coworking Space',
    address: null,
    city: 'Hanoi',
    postalCode: null,
    phoneContact: null,
    emailContact: null,
    website: null,
    shortIntroduction: null,
    aboutUs: null,
    workingTime: null,
    slug: 'megashare-coworking-space',
    isActive: true,
    country: 'Vietnam',
    coworkspace_url: 'vietnam/hanoi/megashare-coworking-space',
    main_image: '/main.jpg',
    main_img: 'jpg',
    min_price: '120000.00',
    currency: 'VND',
    d_price: '120000.00',
    dm_price: '2000000.00',
    is_featured: '0',
    o_rate: '0.0000',
    total: '0',
    xlat: '21.0018285',
    xlng: '105.8229903',
    isEnouvo: false,
    m_price: '1200000.00',
    work_space_id: '8163',
    x_plan: 'FREE',
  },
];

const urlPhoto = 'https://coworker.imgix.net/photos/';

const danangSpace = bussinessesList.filter(
  item => item.city === 'Da Nang' && item.xlat && item.xlng,
);

const danaSpaceWithImage = danangSpace.map(item => {
  return {
    ...item,
    ...{ spaceImage: `${urlPhoto + item.coworkspace_url + item.main_image}` },
  };
});

export { bussinessesList, urlPhoto, danangSpace, danaSpaceWithImage };
